# os environment part

# application environment part
language: node_js
node_js: 
  - "lts/*"

before_install:
  - echo "before install step"
  - pwd
  - ls

install:
  - echo "testing install step"
  - pwd
  - ls

script:
  - echo "testing script step"
  - pwd
  - ls