# os environment part

# application environment part
language: node_js
node_js: 
  - "lts/*"

install:
  - echo "testing install step"
  - npm install

script:
  - echo "testing script step"
  - pwd
  - ls
  - npm run build