# os environment part

# application environment part
matrix:
  include:
    - language: python
      python: 
        - "3.6"
      before_install:
        - cd server/
      install:
        - pip install -r requirements.txt
      script:
        - echo "here should be some tests"
      after_success:
        - echo "here I should start deploy, scp python scripts"
    - language: node_js
      node_js: 
        - "lts/*"
      install:
        - npm install
      script:
        - npm run build
      after_success:
        - echo "here I should start deploy, scp build folder"

notifications:
  email: false